@startuml Criar Serviço
left to right direction
skinparam packageStyle rectangle
actor Prestador
actor Cliente
rectangle Serviços {
  Cliente -- (Cadastrar serviço)
  (Selecionar serviço) -- Prestador
  (Visualizar serviços) .> (Cadastrar serviço) : << include >>
  (Visualizar serviços) -- Prestador 
  Cliente -- (Aceitar Proposta)
  (Enviar proposta) -- Prestador
  (Selecionar serviço) .> (Enviar proposta) : << include >> 
  (Aceitar Proposta).> (Enviar proposta) : << include >>
}
@enduml